# [package]
# name = "lb_be"
# version = "0.1.0"
# edition = "2021"

# [dependencies]

[workspace]
members = [
    "back_end",
    "load_balancer",
]
resolver = "2"

# #load balancer
# [[bin]]
# name = "lb"
# path = "src/lb/main.rs"

# # backend
# [[bin]]
# name = "be"
# path = "src/be/main.rs"